//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidacionesServicio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/Validaciones/", ConfigurationName="ValidacionesServicio.Validaciones")]
    public interface Validaciones
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarNIF", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesServicio.validarNIFResponse> validarNIFAsync(ValidacionesServicio.validarNIFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarNIE", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesServicio.validarNIEResponse> validarNIEAsync(ValidacionesServicio.validarNIERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarNAF", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesServicio.validarNAFResponse> validarNAFAsync(ValidacionesServicio.validarNAFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/Validaciones/validarIBAN", ReplyAction="*")]
        System.Threading.Tasks.Task<ValidacionesServicio.validarIBANResponse> validarIBANAsync(ValidacionesServicio.validarIBANRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIF", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarNIFRequestBody Body;
        
        public validarNIFRequest()
        {
        }
        
        public validarNIFRequest(ValidacionesServicio.validarNIFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nif;
        
        public validarNIFRequestBody()
        {
        }
        
        public validarNIFRequestBody(string nif)
        {
            this.nif = nif;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIFResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarNIFResponseBody Body;
        
        public validarNIFResponse()
        {
        }
        
        public validarNIFResponse(ValidacionesServicio.validarNIFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @out;
        
        public validarNIFResponseBody()
        {
        }
        
        public validarNIFResponseBody(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIE", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarNIERequestBody Body;
        
        public validarNIERequest()
        {
        }
        
        public validarNIERequest(ValidacionesServicio.validarNIERequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIERequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nie;
        
        public validarNIERequestBody()
        {
        }
        
        public validarNIERequestBody(string nie)
        {
            this.nie = nie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNIEResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNIEResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarNIEResponseBody Body;
        
        public validarNIEResponse()
        {
        }
        
        public validarNIEResponse(ValidacionesServicio.validarNIEResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNIEResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @out;
        
        public validarNIEResponseBody()
        {
        }
        
        public validarNIEResponseBody(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNAFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNAF", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarNAFRequestBody Body;
        
        public validarNAFRequest()
        {
        }
        
        public validarNAFRequest(ValidacionesServicio.validarNAFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNAFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string naf;
        
        public validarNAFRequestBody()
        {
        }
        
        public validarNAFRequestBody(string naf)
        {
            this.naf = naf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarNAFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarNAFResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarNAFResponseBody Body;
        
        public validarNAFResponse()
        {
        }
        
        public validarNAFResponse(ValidacionesServicio.validarNAFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarNAFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @out;
        
        public validarNAFResponseBody()
        {
        }
        
        public validarNAFResponseBody(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBAN", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarIBANRequestBody Body;
        
        public validarIBANRequest()
        {
        }
        
        public validarIBANRequest(ValidacionesServicio.validarIBANRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iban;
        
        public validarIBANRequestBody()
        {
        }
        
        public validarIBANRequestBody(string iban)
        {
            this.iban = iban;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarIBANResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarIBANResponse", Namespace="http://www.example.org/Validaciones/", Order=0)]
        public ValidacionesServicio.validarIBANResponseBody Body;
        
        public validarIBANResponse()
        {
        }
        
        public validarIBANResponse(ValidacionesServicio.validarIBANResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarIBANResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @out;
        
        public validarIBANResponseBody()
        {
        }
        
        public validarIBANResponseBody(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ValidacionesChannel : ValidacionesServicio.Validaciones, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ValidacionesClient : System.ServiceModel.ClientBase<ValidacionesServicio.Validaciones>, ValidacionesServicio.Validaciones
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ValidacionesClient() : 
                base(ValidacionesClient.GetDefaultBinding(), ValidacionesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ValidacionesSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(EndpointConfiguration endpointConfiguration) : 
                base(ValidacionesClient.GetBindingForEndpoint(endpointConfiguration), ValidacionesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ValidacionesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ValidacionesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ValidacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesServicio.validarNIFResponse> ValidacionesServicio.Validaciones.validarNIFAsync(ValidacionesServicio.validarNIFRequest request)
        {
            return base.Channel.validarNIFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesServicio.validarNIFResponse> validarNIFAsync(string nif)
        {
            ValidacionesServicio.validarNIFRequest inValue = new ValidacionesServicio.validarNIFRequest();
            inValue.Body = new ValidacionesServicio.validarNIFRequestBody();
            inValue.Body.nif = nif;
            return ((ValidacionesServicio.Validaciones)(this)).validarNIFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesServicio.validarNIEResponse> ValidacionesServicio.Validaciones.validarNIEAsync(ValidacionesServicio.validarNIERequest request)
        {
            return base.Channel.validarNIEAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesServicio.validarNIEResponse> validarNIEAsync(string nie)
        {
            ValidacionesServicio.validarNIERequest inValue = new ValidacionesServicio.validarNIERequest();
            inValue.Body = new ValidacionesServicio.validarNIERequestBody();
            inValue.Body.nie = nie;
            return ((ValidacionesServicio.Validaciones)(this)).validarNIEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesServicio.validarNAFResponse> ValidacionesServicio.Validaciones.validarNAFAsync(ValidacionesServicio.validarNAFRequest request)
        {
            return base.Channel.validarNAFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesServicio.validarNAFResponse> validarNAFAsync(string naf)
        {
            ValidacionesServicio.validarNAFRequest inValue = new ValidacionesServicio.validarNAFRequest();
            inValue.Body = new ValidacionesServicio.validarNAFRequestBody();
            inValue.Body.naf = naf;
            return ((ValidacionesServicio.Validaciones)(this)).validarNAFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ValidacionesServicio.validarIBANResponse> ValidacionesServicio.Validaciones.validarIBANAsync(ValidacionesServicio.validarIBANRequest request)
        {
            return base.Channel.validarIBANAsync(request);
        }
        
        public System.Threading.Tasks.Task<ValidacionesServicio.validarIBANResponse> validarIBANAsync(string iban)
        {
            ValidacionesServicio.validarIBANRequest inValue = new ValidacionesServicio.validarIBANRequest();
            inValue.Body = new ValidacionesServicio.validarIBANRequestBody();
            inValue.Body.iban = iban;
            return ((ValidacionesServicio.Validaciones)(this)).validarIBANAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidacionesSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ValidacionesSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/p1/services/Validaciones/");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ValidacionesClient.GetBindingForEndpoint(EndpointConfiguration.ValidacionesSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ValidacionesClient.GetEndpointAddress(EndpointConfiguration.ValidacionesSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            ValidacionesSOAP,
        }
    }
}
