//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlAccesosServicio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/ControlAccesos/", ConfigurationName="ControlAccesosServicio.ControlAccesos")]
    public interface ControlAccesos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ControlAccesos/registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlAccesosServicio.registrarResponse> registrarAsync(ControlAccesosServicio.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ControlAccesos/consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlAccesosServicio.consultarResponse> consultarAsync(ControlAccesosServicio.consultarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrar", WrapperNamespace="http://www.example.org/ControlAccesos/", IsWrapped=true)]
    public partial class registrarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nif;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigosala;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigodispositivo;
        
        public registrarRequest()
        {
        }
        
        public registrarRequest(string nif, int codigosala, int codigodispositivo)
        {
            this.nif = nif;
            this.codigosala = codigosala;
            this.codigodispositivo = codigodispositivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarResponse", WrapperNamespace="http://www.example.org/ControlAccesos/", IsWrapped=true)]
    public partial class registrarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @out;
        
        public registrarResponse()
        {
        }
        
        public registrarResponse(bool @out)
        {
            this.@out = @out;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ControlAccesos/")]
    public partial class registroaccesos
    {
        
        private int idField;
        
        private int idEmpleadoField;
        
        private int idSalaField;
        
        private int idDispositivoField;
        
        private System.DateTime fechaHoraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEmpleado
        {
            get
            {
                return this.idEmpleadoField;
            }
            set
            {
                this.idEmpleadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idSala
        {
            get
            {
                return this.idSalaField;
            }
            set
            {
                this.idSalaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idDispositivo
        {
            get
            {
                return this.idDispositivoField;
            }
            set
            {
                this.idDispositivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaHora
        {
            get
            {
                return this.fechaHoraField;
            }
            set
            {
                this.fechaHoraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar", WrapperNamespace="http://www.example.org/ControlAccesos/", IsWrapped=true)]
    public partial class consultarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nif;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigosala;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigodispositivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        public consultarRequest()
        {
        }
        
        public consultarRequest(string nif, int codigosala, int codigodispositivo, string fechaInc, string fechaFin)
        {
            this.nif = nif;
            this.codigosala = codigosala;
            this.codigodispositivo = codigodispositivo;
            this.fechaInc = fechaInc;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarResponse", WrapperNamespace="http://www.example.org/ControlAccesos/", IsWrapped=true)]
    public partial class consultarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlAccesos/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("registroccesos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ControlAccesosServicio.registroaccesos[] @out;
        
        public consultarResponse()
        {
        }
        
        public consultarResponse(ControlAccesosServicio.registroaccesos[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ControlAccesosChannel : ControlAccesosServicio.ControlAccesos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ControlAccesosClient : System.ServiceModel.ClientBase<ControlAccesosServicio.ControlAccesos>, ControlAccesosServicio.ControlAccesos
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ControlAccesosClient() : 
                base(ControlAccesosClient.GetDefaultBinding(), ControlAccesosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ControlAccesosSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlAccesosClient(EndpointConfiguration endpointConfiguration) : 
                base(ControlAccesosClient.GetBindingForEndpoint(endpointConfiguration), ControlAccesosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlAccesosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ControlAccesosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlAccesosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ControlAccesosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlAccesosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlAccesosServicio.registrarResponse> ControlAccesosServicio.ControlAccesos.registrarAsync(ControlAccesosServicio.registrarRequest request)
        {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlAccesosServicio.registrarResponse> registrarAsync(string nif, int codigosala, int codigodispositivo)
        {
            ControlAccesosServicio.registrarRequest inValue = new ControlAccesosServicio.registrarRequest();
            inValue.nif = nif;
            inValue.codigosala = codigosala;
            inValue.codigodispositivo = codigodispositivo;
            return ((ControlAccesosServicio.ControlAccesos)(this)).registrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlAccesosServicio.consultarResponse> ControlAccesosServicio.ControlAccesos.consultarAsync(ControlAccesosServicio.consultarRequest request)
        {
            return base.Channel.consultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlAccesosServicio.consultarResponse> consultarAsync(string nif, int codigosala, int codigodispositivo, string fechaInc, string fechaFin)
        {
            ControlAccesosServicio.consultarRequest inValue = new ControlAccesosServicio.consultarRequest();
            inValue.nif = nif;
            inValue.codigosala = codigosala;
            inValue.codigodispositivo = codigodispositivo;
            inValue.fechaInc = fechaInc;
            inValue.fechaFin = fechaFin;
            return ((ControlAccesosServicio.ControlAccesos)(this)).consultarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControlAccesosSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControlAccesosSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/p1/services/ControlAccesos/");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ControlAccesosClient.GetBindingForEndpoint(EndpointConfiguration.ControlAccesosSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ControlAccesosClient.GetEndpointAddress(EndpointConfiguration.ControlAccesosSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            ControlAccesosSOAP,
        }
    }
}
