//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadosServicio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/empleados/", ConfigurationName="EmpleadosServicio.empleados")]
    public interface empleados
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/empleados/nuevo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmpleadosServicio.nuevoResponse> nuevoAsync(EmpleadosServicio.nuevoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/empleados/borrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmpleadosServicio.borrarResponse> borrarAsync(EmpleadosServicio.borrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/empleados/modificar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmpleadosServicio.modificarResponse> modificarAsync(EmpleadosServicio.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/empleados/consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmpleadosServicio.consultarResponse> consultarAsync(EmpleadosServicio.consultarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/empleados/")]
    public partial class Empleado
    {
        
        private int idField;
        
        private string nifnieField;
        
        private string nombreApellidosField;
        
        private string emailField;
        
        private string nafField;
        
        private string ibanField;
        
        private int idNivelField;
        
        private string usuarioField;
        
        private string passwordField;
        
        private bool validoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nifnie
        {
            get
            {
                return this.nifnieField;
            }
            set
            {
                this.nifnieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreApellidos
        {
            get
            {
                return this.nombreApellidosField;
            }
            set
            {
                this.nombreApellidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string naf
        {
            get
            {
                return this.nafField;
            }
            set
            {
                this.nafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string iban
        {
            get
            {
                return this.ibanField;
            }
            set
            {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idNivel
        {
            get
            {
                return this.idNivelField;
            }
            set
            {
                this.idNivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool valido
        {
            get
            {
                return this.validoField;
            }
            set
            {
                this.validoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nuevo", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class nuevoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmpleadosServicio.Empleado @in;
        
        public nuevoRequest()
        {
        }
        
        public nuevoRequest(EmpleadosServicio.Empleado @in)
        {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nuevoResponse", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class nuevoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @out;
        
        public nuevoResponse()
        {
        }
        
        public nuevoResponse(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="borrar", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class borrarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nif;
        
        public borrarRequest()
        {
        }
        
        public borrarRequest(string nif)
        {
            this.nif = nif;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="borrarResponse", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class borrarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @out;
        
        public borrarResponse()
        {
        }
        
        public borrarResponse(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class modificarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmpleadosServicio.Empleado @in;
        
        public modificarRequest()
        {
        }
        
        public modificarRequest(EmpleadosServicio.Empleado @in)
        {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class modificarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @out;
        
        public modificarResponse()
        {
        }
        
        public modificarResponse(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class consultarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nif;
        
        public consultarRequest()
        {
        }
        
        public consultarRequest(string nif)
        {
            this.nif = nif;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarResponse", WrapperNamespace="http://www.example.org/empleados/", IsWrapped=true)]
    public partial class consultarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/empleados/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmpleadosServicio.Empleado @out;
        
        public consultarResponse()
        {
        }
        
        public consultarResponse(EmpleadosServicio.Empleado @out)
        {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface empleadosChannel : EmpleadosServicio.empleados, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class empleadosClient : System.ServiceModel.ClientBase<EmpleadosServicio.empleados>, EmpleadosServicio.empleados
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public empleadosClient() : 
                base(empleadosClient.GetDefaultBinding(), empleadosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.empleadosSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public empleadosClient(EndpointConfiguration endpointConfiguration) : 
                base(empleadosClient.GetBindingForEndpoint(endpointConfiguration), empleadosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public empleadosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(empleadosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public empleadosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(empleadosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public empleadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpleadosServicio.nuevoResponse> EmpleadosServicio.empleados.nuevoAsync(EmpleadosServicio.nuevoRequest request)
        {
            return base.Channel.nuevoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpleadosServicio.nuevoResponse> nuevoAsync(EmpleadosServicio.Empleado @in)
        {
            EmpleadosServicio.nuevoRequest inValue = new EmpleadosServicio.nuevoRequest();
            inValue.@in = @in;
            return ((EmpleadosServicio.empleados)(this)).nuevoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpleadosServicio.borrarResponse> EmpleadosServicio.empleados.borrarAsync(EmpleadosServicio.borrarRequest request)
        {
            return base.Channel.borrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpleadosServicio.borrarResponse> borrarAsync(string nif)
        {
            EmpleadosServicio.borrarRequest inValue = new EmpleadosServicio.borrarRequest();
            inValue.nif = nif;
            return ((EmpleadosServicio.empleados)(this)).borrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpleadosServicio.modificarResponse> EmpleadosServicio.empleados.modificarAsync(EmpleadosServicio.modificarRequest request)
        {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpleadosServicio.modificarResponse> modificarAsync(EmpleadosServicio.Empleado @in)
        {
            EmpleadosServicio.modificarRequest inValue = new EmpleadosServicio.modificarRequest();
            inValue.@in = @in;
            return ((EmpleadosServicio.empleados)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpleadosServicio.consultarResponse> EmpleadosServicio.empleados.consultarAsync(EmpleadosServicio.consultarRequest request)
        {
            return base.Channel.consultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpleadosServicio.consultarResponse> consultarAsync(string nif)
        {
            EmpleadosServicio.consultarRequest inValue = new EmpleadosServicio.consultarRequest();
            inValue.nif = nif;
            return ((EmpleadosServicio.empleados)(this)).consultarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.empleadosSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.empleadosSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/p1/services/empleados/");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return empleadosClient.GetBindingForEndpoint(EndpointConfiguration.empleadosSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return empleadosClient.GetEndpointAddress(EndpointConfiguration.empleadosSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            empleadosSOAP,
        }
    }
}
