//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPresenciaServicio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/ControlPresencia/", ConfigurationName="ControlPresenciaServicio.ControlPresencia")]
    public interface ControlPresencia
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ControlPresencia/registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlPresenciaServicio.registrarResponse> registrarAsync(ControlPresenciaServicio.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ControlPresencia/eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlPresenciaServicio.eliminarResponse> eliminarAsync(ControlPresenciaServicio.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ControlPresencia/controlEmpleadosSala", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ControlPresenciaServicio.controlEmpleadosSalaResponse> controlEmpleadosSalaAsync(ControlPresenciaServicio.controlEmpleadosSalaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrar", WrapperNamespace="http://www.example.org/ControlPresencia/", IsWrapped=true)]
    public partial class registrarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nif;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigosala;
        
        public registrarRequest()
        {
        }
        
        public registrarRequest(string nif, int codigosala)
        {
            this.nif = nif;
            this.codigosala = codigosala;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarResponse", WrapperNamespace="http://www.example.org/ControlPresencia/", IsWrapped=true)]
    public partial class registrarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @out;
        
        public registrarResponse()
        {
        }
        
        public registrarResponse(bool @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://www.example.org/ControlPresencia/", IsWrapped=true)]
    public partial class eliminarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nif;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigosala;
        
        public eliminarRequest()
        {
        }
        
        public eliminarRequest(string nif, int codigosala)
        {
            this.nif = nif;
            this.codigosala = codigosala;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://www.example.org/ControlPresencia/", IsWrapped=true)]
    public partial class eliminarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @out;
        
        public eliminarResponse()
        {
        }
        
        public eliminarResponse(bool @out)
        {
            this.@out = @out;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ControlPresencia/")]
    public partial class Empleado
    {
        
        private int idField;
        
        private string nifnieField;
        
        private string nombreApellidosField;
        
        private string emailField;
        
        private string nafField;
        
        private string ibanField;
        
        private int idNivelField;
        
        private string usuarioField;
        
        private string passwordField;
        
        private bool validoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nifnie
        {
            get
            {
                return this.nifnieField;
            }
            set
            {
                this.nifnieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreApellidos
        {
            get
            {
                return this.nombreApellidosField;
            }
            set
            {
                this.nombreApellidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string naf
        {
            get
            {
                return this.nafField;
            }
            set
            {
                this.nafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string iban
        {
            get
            {
                return this.ibanField;
            }
            set
            {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idNivel
        {
            get
            {
                return this.idNivelField;
            }
            set
            {
                this.idNivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool valido
        {
            get
            {
                return this.validoField;
            }
            set
            {
                this.validoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="controlEmpleadosSala", WrapperNamespace="http://www.example.org/ControlPresencia/", IsWrapped=true)]
    public partial class controlEmpleadosSalaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigosala;
        
        public controlEmpleadosSalaRequest()
        {
        }
        
        public controlEmpleadosSalaRequest(int codigosala)
        {
            this.codigosala = codigosala;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="controlEmpleadosSalaResponse", WrapperNamespace="http://www.example.org/ControlPresencia/", IsWrapped=true)]
    public partial class controlEmpleadosSalaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ControlPresencia/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("empleados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ControlPresenciaServicio.Empleado[] @out;
        
        public controlEmpleadosSalaResponse()
        {
        }
        
        public controlEmpleadosSalaResponse(ControlPresenciaServicio.Empleado[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ControlPresenciaChannel : ControlPresenciaServicio.ControlPresencia, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ControlPresenciaClient : System.ServiceModel.ClientBase<ControlPresenciaServicio.ControlPresencia>, ControlPresenciaServicio.ControlPresencia
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ControlPresenciaClient() : 
                base(ControlPresenciaClient.GetDefaultBinding(), ControlPresenciaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ControlPresenciaSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlPresenciaClient(EndpointConfiguration endpointConfiguration) : 
                base(ControlPresenciaClient.GetBindingForEndpoint(endpointConfiguration), ControlPresenciaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlPresenciaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ControlPresenciaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlPresenciaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ControlPresenciaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ControlPresenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlPresenciaServicio.registrarResponse> ControlPresenciaServicio.ControlPresencia.registrarAsync(ControlPresenciaServicio.registrarRequest request)
        {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlPresenciaServicio.registrarResponse> registrarAsync(string nif, int codigosala)
        {
            ControlPresenciaServicio.registrarRequest inValue = new ControlPresenciaServicio.registrarRequest();
            inValue.nif = nif;
            inValue.codigosala = codigosala;
            return ((ControlPresenciaServicio.ControlPresencia)(this)).registrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlPresenciaServicio.eliminarResponse> ControlPresenciaServicio.ControlPresencia.eliminarAsync(ControlPresenciaServicio.eliminarRequest request)
        {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlPresenciaServicio.eliminarResponse> eliminarAsync(string nif, int codigosala)
        {
            ControlPresenciaServicio.eliminarRequest inValue = new ControlPresenciaServicio.eliminarRequest();
            inValue.nif = nif;
            inValue.codigosala = codigosala;
            return ((ControlPresenciaServicio.ControlPresencia)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlPresenciaServicio.controlEmpleadosSalaResponse> ControlPresenciaServicio.ControlPresencia.controlEmpleadosSalaAsync(ControlPresenciaServicio.controlEmpleadosSalaRequest request)
        {
            return base.Channel.controlEmpleadosSalaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlPresenciaServicio.controlEmpleadosSalaResponse> controlEmpleadosSalaAsync(int codigosala)
        {
            ControlPresenciaServicio.controlEmpleadosSalaRequest inValue = new ControlPresenciaServicio.controlEmpleadosSalaRequest();
            inValue.codigosala = codigosala;
            return ((ControlPresenciaServicio.ControlPresencia)(this)).controlEmpleadosSalaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControlPresenciaSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ControlPresenciaSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/p1/services/ControlPresencia/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ControlPresenciaClient.GetBindingForEndpoint(EndpointConfiguration.ControlPresenciaSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ControlPresenciaClient.GetEndpointAddress(EndpointConfiguration.ControlPresenciaSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            ControlPresenciaSOAP,
        }
    }
}
